version: "3.8"

services:
  domingo:
    build:
      context: ./domingo
    container_name: domingo_container

  paula:
    build:
      context: ./Paula
    container_name: paula_container

  antonio:
    build:
      context: ./Antonio
    container_name: antonio_container

  lucia:
    build:
      context: ./Lucia
    container_name: lucia_container

  fcojvrmn:
    build:
      context: ./fcojvrmn
    container_name: fcojvrmn_container

  alvaro:
    build:
      context: ./alvaro
    container_name: contenedor_alvaro

  josealejandrogc94:
    build:
      context: ./josealejandrogc94
    container_name: josealejandrogc94_container

  hector:
    build:
      context: ./hector
    container_name: hector_container
